export default function Emoji({value,updateFunc}) {
  return (
    <div style={{overflow:"auto"}} onClick={(e) => {
        if (e.target.innerHTML.length === 2) {
            updateFunc(value + e.target.innerHTML);
        }
      }}>
      <span>😀</span>
      <span>😃</span>
      <span>😄</span>
      <span>😁</span>
      <span>😆</span>
      <span>😅</span>
      <span>😂</span>
      <span>🤣</span>
      <span>🥲</span>
      <span>😊</span>
      <span>😇</span>
      <span>🙂</span>
      <span>🙃</span>
      <span>😉</span>
      <span>😌</span>
      <span>😍</span>
      <span>🥰</span>
      <span>😘</span>
      <span>😗</span>
      <span>😙</span>
      <span>😚</span>
      <span>😋</span>
      <span>😛</span>
      <span>😝</span>
      <span>😜</span>
      <span>🤪</span>
      <span>🤨</span>
      <span>🧐</span>
      <span>🤓</span>
      <span>😎</span>
      <span>🥸</span>
      <span>🤩</span>
      <span>🥳</span>
      <span>😏</span>
      <span>😒</span>
      <span>😞</span>
      <span>😔</span>
      <span>😟</span>
      <span>😕</span>
      <span>🙁</span>
      <span>☹️</span>
      <span>😣</span>
      <span>😖</span>
      <span>😫</span>
      <span>😩</span>
      <span>🥺</span>
      <span>😢</span>
      <span>😭</span>
      <span>😤</span>
      <span>😠</span>
      <span>😡</span>
      <span>🤬</span>
      <span>🤯</span>
      <span>😳</span>
      <span>🥵</span>
      <span>🥶</span>
      <span>😱</span>
      <span>😨</span>
      <span>😰</span>
      <span>😥</span>
      <span>😓</span>
      <span>🤗</span>
      <span>🤔</span>
      <span>🤭</span>
      <span>🤫</span>
      <span>🤥</span>
      <span>😶</span>
      <span>😐</span>
      <span>😑</span>
      <span>😬</span>
      <span>🙄</span>
      <span>😯</span>
      <span>😦</span>
      <span>😧</span>
      <span>😮</span>
      <span>😲</span>
      <span>🥱</span>
      <span>😴</span>
      <span>🤤</span>
      <span>😪</span>
      <span>😵</span>
      <span>🤐</span>
      <span>🥴</span>
      <span>🤢</span>
      <span>🤮</span>
      <span>🤧</span>
      <span>😷</span>
      <span>🤒</span>
      <span>🤕</span>
      <span>🤑</span>
      <span>🤠</span>
      <span>😈</span>
      <span>👿</span>
      <span>👹</span>
      <span>👺</span>
      <span>🤡</span>
      <span>💩</span>
      <span>👻</span>
      <span>💀</span>
      <span>☠️</span>
      <span>👽</span>
      <span>👾</span>
      <span>🤖</span>
      <span>🎃</span>
      <span>😺</span>
      <span>😸</span>
      <span>😹</span>
      <span>😻</span>
      <span>😼</span>
      <span>😽</span>
      <span>🙀</span>
      <span>😿</span>
      <span>😾</span>
    </div>
  );
}
